### ISSUE TITLE
CheckList

### ISSUE THREAD

**Issue by tiagobalm** [centeio/lbaw#18]
- [x]     Implement user management.
- [x]     Implement support for mobile devices.
- [ ]     Implement an information search system using the full-text search features of PostgreSQL.
- [x]     Implementing online assistance (e.g. help online) in the product.
- [ ]     Ensure isolation of various system layers (SQL, PHP, and HTML/CSS/JSON) with technologies such as PDO and Smarty.
- [ ]     Implement an architecture to handle internal errors.
- [x]     Use AJAX in web pages.
- [ ]     Validate data entered by the user in forms using HTML5.
- [x]     Validate data entered by the user in forms using JavaScript.
- [x]     Validate data entered by the user in forms using PHP.
- [ ]     Implement access control.
- [ ]     Check the HTML and CSS using the W3C validation tools.
- [ ]     Check the accessibility of interfaces using automated tools.
- [ ]     Check the usability of the product based on lists of common web usability problems.
- [ ]     Remove test and development comments from source code.
- [ ]     Remove temporary or unused files from the delivered source code.
- [ ]     Include the source code in a single .zip file attached in the wiki page of the product.
- [ ]     Include a list of features in the product wiki page, indicating the implementation status of each feature (as a percentage).
- [ ]     Display the URL of the product on the wiki page.
- [ ]     Include product access credentials (with different levels of permissions) on the wiki page.
- [ ]     Prepare and include in the wiki page a promotional video of the product (2 minutes maximum).
- [ ]     Remove test data from the database.
- [ ]     Populate the database with good (realistic) examples.
- [ ]     Prepare the script for product demonstration.
